package net.techandgraphics.hymn

import androidx.annotation.DrawableRes
import net.techandgraphics.hymn.data.local.entities.SearchEntity

data class Category(
  val categoryId: Int,
  @DrawableRes
  val drawableRes: Int
)

object Constant {
  val images = arrayListOf(
    Category(1, R.drawable.im_word_of_god),
    Category(2, R.drawable.im_creation),
    Category(3, R.drawable.im_providence),
    Category(4, R.drawable.im_redemption),
    Category(5, R.drawable.im_incarnation),
    Category(6, R.drawable.im_example),
    Category(7, R.drawable.im_suffering_and_death),
    Category(8, R.drawable.im_resurrection),
    Category(9, R.drawable.im_glory),
    Category(10, R.drawable.im_help),
    Category(11, R.drawable.im_coming_again),
    Category(12, R.drawable.im_praise),
    Category(13, R.drawable.im_holy_spirit),
    Category(14, R.drawable.im_word_of_god),
    Category(15, R.drawable.im_gospel),
    Category(16, R.drawable.im_repentance),
    Category(17, R.drawable.im_love_and_gratitude),
    Category(18, R.drawable.im_joy_and_peace),
    Category(19, R.drawable.im_faith),
    Category(20, R.drawable.im_holiness),
    Category(21, R.drawable.im_service),
    Category(22, R.drawable.im_conflict_and_templation),
    Category(23, R.drawable.im_pilgrimage),
    Category(24, R.drawable.im_death),
    Category(25, R.drawable.im_heavenly_glory),
    Category(26, R.drawable.im_prayer),
    Category(27, R.drawable.im_church),
    Category(28, R.drawable.im_morning_prayer),
    Category(29, R.drawable.im_evening_player),
    Category(30, R.drawable.im_lords_day),
    Category(31, R.drawable.im_house_of_the_lord),
    Category(32, R.drawable.im_worship_and_praise),
    Category(33, R.drawable.im_baptism),
    Category(34, R.drawable.im_church),
    Category(35, R.drawable.im_glory),
    Category(36, R.drawable.im_conflict_and_templation),
    Category(37, R.drawable.im_praise),
    Category(38, R.drawable.im_redemption),
    Category(38, R.drawable.im_resurrection),
    Category(39, R.drawable.im_gospel),
    Category(40, R.drawable.im_new_year),
    Category(41, R.drawable.im_seed_time_and_harvest),
    Category(42, R.drawable.im_lords_day),
    Category(43, R.drawable.im_holiness),
    Category(44, R.drawable.im_pilgrimage),
    Category(45, R.drawable.im_death),
    Category(46, R.drawable.im_faith),
    Category(47, R.drawable.im_lords_day),
    Category(48, R.drawable.im_providence),
    Category(49, R.drawable.im_resurrection),
    Category(50, R.drawable.im_church),
    Category(51, R.drawable.im_example),
    Category(52, R.drawable.im_holiness),
    Category(53, R.drawable.im_death),
    Category(54, R.drawable.im_gospel),
    Category(55, R.drawable.im_holy_trinity),
    Category(56, R.drawable.im_conflict_and_templation),

    Category(56 + 1, R.drawable.im_word_of_god),
    Category(56 + 2, R.drawable.im_creation),
    Category(56 + 3, R.drawable.im_providence),
    Category(56 + 4, R.drawable.im_redemption),
    Category(56 + 5, R.drawable.im_incarnation),
    Category(56 + 6, R.drawable.im_example),
    Category(56 + 7, R.drawable.im_suffering_and_death),
    Category(56 + 8, R.drawable.im_resurrection),
    Category(56 + 9, R.drawable.im_glory),
    Category(56 + 10, R.drawable.im_help),
    Category(56 + 11, R.drawable.im_coming_again),
    Category(56 + 12, R.drawable.im_praise),
    Category(56 + 13, R.drawable.im_holy_spirit),
    Category(56 + 14, R.drawable.im_word_of_god),
    Category(56 + 15, R.drawable.im_gospel),
    Category(56 + 16, R.drawable.im_repentance),
    Category(56 + 17, R.drawable.im_love_and_gratitude),
    Category(56 + 18, R.drawable.im_joy_and_peace),
    Category(56 + 19, R.drawable.im_faith),
    Category(56 + 20, R.drawable.im_holiness),
    Category(56 + 21, R.drawable.im_service),
    Category(56 + 22, R.drawable.im_conflict_and_templation),
    Category(56 + 23, R.drawable.im_pilgrimage),
    Category(56 + 24, R.drawable.im_death),
    Category(56 + 25, R.drawable.im_heavenly_glory),
    Category(56 + 26, R.drawable.im_prayer),
    Category(56 + 27, R.drawable.im_church),
    Category(56 + 28, R.drawable.im_morning_prayer),
    Category(56 + 29, R.drawable.im_evening_player),
    Category(56 + 30, R.drawable.im_lords_day),
    Category(56 + 31, R.drawable.im_house_of_the_lord),
    Category(56 + 32, R.drawable.im_worship_and_praise),
    Category(56 + 33, R.drawable.im_baptism),
    Category(56 + 34, R.drawable.im_church),
    Category(56 + 35, R.drawable.im_glory),
    Category(56 + 36, R.drawable.im_conflict_and_templation),
    Category(56 + 37, R.drawable.im_praise),
    Category(56 + 38, R.drawable.im_redemption),
    Category(56 + 38, R.drawable.im_resurrection),
    Category(56 + 39, R.drawable.im_gospel),
    Category(56 + 40, R.drawable.im_new_year),
    Category(56 + 41, R.drawable.im_seed_time_and_harvest),
    Category(56 + 42, R.drawable.im_lords_day),
    Category(56 + 43, R.drawable.im_holiness),
    Category(56 + 44, R.drawable.im_pilgrimage),
    Category(56 + 45, R.drawable.im_death),
    Category(56 + 46, R.drawable.im_faith),
    Category(56 + 47, R.drawable.im_lords_day),
    Category(56 + 48, R.drawable.im_providence),
    Category(56 + 49, R.drawable.im_resurrection),
    Category(56 + 50, R.drawable.im_faith),
    Category(56 + 51, R.drawable.im_example),
    Category(56 + 52, R.drawable.im_holiness),
    Category(56 + 53, R.drawable.im_death),
    Category(56 + 54, R.drawable.im_gospel),
    Category(56 + 55, R.drawable.im_holy_trinity),
    Category(56 + 56, R.drawable.im_conflict_and_templation),
    Category(56 + 57, R.drawable.im_hope_and_comfort),
    Category(56 + 58, R.drawable.im_faithfulness_of_god),
    Category(56 + 59, R.drawable.im_joy_and_peace),
    Category(56 + 60, R.drawable.im_our_love_for_god),
    Category(56 + 61, R.drawable.im_our_love_for_god),
    Category(56 + 62, R.drawable.im_contemporary_hymns),
    Category(56 + 63, R.drawable.im_community_in_christ),
  )

  val searchEntityTags = arrayListOf(
    SearchEntity(query = "Amazing grace", tag = "amazinggrace"),
    SearchEntity(query = "I need thee", tag = "ineedthee"),
    SearchEntity(query = "What a friend", tag = "whatafriend"),
    SearchEntity(query = "200", tag = "200"),
    SearchEntity(query = "Holy Spirit", tag = "holyspirit"),
    SearchEntity(query = "Pass me not", tag = "passmenot"),

    SearchEntity(query = "Unakhetsedwa mwazi", tag = "unakhetsedwamwazi", lang = "ch"),
    SearchEntity(query = "Ndi mitima", tag = "ndimitima", lang = "ch"),
    SearchEntity(query = "Wina atikonda ife", tag = "Winaatikondaife", lang = "ch"),
    SearchEntity(query = "Pokhala mtendere", tag = "pokhalamtendere", lang = "ch"),
    SearchEntity(query = "Mtima wa Mbuyako", tag = "mtimawambuyako", lang = "ch"),
    SearchEntity(query = "Bwezatu", tag = "bwezatu", lang = "ch"),
  )

  val ofTheDay = arrayListOf(
    R.drawable.of_the_day1420830,
    R.drawable.of_the_day1835447,
    R.drawable.of_the_day3123468,
    R.drawable.of_the_day3587237,
    R.drawable.of_the_day5842978,
  )
}
